### ISSUE TITLE
我能加入维护吗？

### ISSUE THREAD

**Issue by Aver58** [XINCGer/ColaFrameWork#1]
我是工作1年多的U3D程序，想说可以一起跟你一起维护学习一下吗？

**Comment by XINCGer** [comment]
> 我是工作1年多的U3D程序，想说可以一起跟你一起维护学习一下吗？

话说，我回粉你了，哈哈

**Comment by Aver58** [comment]
er~~~,整了大半天没整下来，没有搞过这个，我fork了，好像克隆不下来，需要权限吗?我看网上好像还要ssh？？

**Comment by XINCGer** [comment]
> er~~~,整了大半天没整下来，没有搞过这个，我fork了，好像克隆不下来，需要权限吗?我看网上好像还要ssh？？

一般开发流程如下：
1.fork一份工程到自己的账户里面；
2.配置自己账户的ssh，并且在本地安装适合的git客户端工具；
3.在自己的分支进行提交；
4.发起对我的分支的pull request，请求合并；
5.我合并，Merge你的分支并解决冲突等；

**Comment by Aver58** [comment]
试了一下

**Comment by XINCGer** [comment]
> 试了一下

合并了，我猜你是每天9点下班，蛤蛤
