### ISSUE TITLE
middleclass如何被c#调用的问题

### ISSUE THREAD

**Issue by GITHUB243884919** [XINCGer/ColaFrameWork#4]
StateLogin.lua如下，在Main.lua同目录
`local StateLogin = Class('StateLogin')

function StateLogin.Enter()
    print("lua StateLogin Enter")
end

StateLogin = StateLogin:new()

return StateLogin`

然后在c#代码中调用StateLogin.Entertolua报找不到这个函数的错误。
`        luaState.DoFile("Main.lua");
        levelLoaded = luaState.GetFunction("OnLevelWasLoaded");
        CallMain();
        luaState.DoFile("StateLogin.lua");
        luaState.GetFunction("StateLogin.Enter").Call();`

但是如果lua中我不用这个middleclass，而是直接用table的定义就没问题

`StateLogin = {}
function StateLogin:Enter()
    print("lua StateLogin Enter")
end`

请教下这是什么问题？如何解决

**Comment by tanyuqing** [comment]
暂时没时间验证，猜测一下：
1、中间类的问题，需要看里边做了啥 
2、访问范围问题，你的第二种写法没加local


希望能帮到你.





------------------ 原始邮件 ------------------
发件人: "GITHUB243884919"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 下午3:15
收件人: "XINCGer/ColaFrameWork"<ColaFrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [XINCGer/ColaFrameWork] middleclass如何被c#调用的问题 (#4)




StateLogin.lua如下，在Main.lua同目录
 `local StateLogin = Class('StateLogin')
 
function StateLogin.Enter()
 print("lua StateLogin Enter")
 end
 
StateLogin = StateLogin:new()
 
return StateLogin然后在c#代码中调用StateLogin.Entertolua报找不到这个函数的错误。        luaState.DoFile("Main.lua");
 levelLoaded = luaState.GetFunction("OnLevelWasLoaded");
 CallMain();
 luaState.DoFile("StateLogin.lua");
 luaState.GetFunction("StateLogin.Enter").Call();`
 
但是如果lua中我不用这个middleclass，而是直接用table的定义就没问题
 StateLogin = {} function StateLogin:Enter() print("lua StateLogin Enter") end
 请教下这是什么问题？如何解决

**Comment by GITHUB243884919** [comment]
是的，第二种写法没写local。我是关闭了你的全局变量检查 --require("Utilitys.LuaGlobalCheck")。
第二种写法如果写成local也是没法调用的。
难道你们不会涉及c#调用中间类写的lua？

**Comment by tanyuqing** [comment]
很少用到
初始化的时候会有c#调用lua，其它时间多都是lua调c#。


我给你看下那个例子的写法


加个QQ吧：594006414





------------------ 原始邮件 ------------------
发件人: "GITHUB243884919"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 下午3:40
收件人: "XINCGer/ColaFrameWork"<ColaFrameWork@noreply.github.com>;
抄送: "谈宇卿"<tan-yuqing@foxmail.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [XINCGer/ColaFrameWork] middleclass如何被c#调用的问题 (#4)




是的，第二种写法没写local。我是关闭了你的全局变量检查 --require("Utilitys.LuaGlobalCheck")。
 第二种写法如果写成local也是没法调用的。
 难道你们不会涉及c#调用中间类写的lua？

**Comment by XINCGer** [comment]
你好，我来回答一下您的这个问题，在toLua中没有办法直接访问到local 的这种局部变量的。如果想要访问的话可以通过把你的类注册到一个全局的table中进行访问。比如将你的方法注册到UIManager的TestOpen中，然后就可以在C#端通过访问UIManger的方式进行访问了，代码如下：

```C#  luaState.DoFile("Main.lua");
        levelLoaded = luaState.GetFunction("OnLevelWasLoaded");
        CallMain();

        LuaTable uiManager = luaState.GetTable("UIManager");
        var func = uiManager.GetLuaFunction("TestOpen");
        func.Call();
```
或者你也可以将你的table通过某种方式传到C#中，并使用LuaTable类型的变量持有引用，然后在进行访问。不过不建议过多的进行C#和lua的这种穿梭操作，对性能消耗比较大，能完成的业务尽量就在lua端完成，或者在C#端封装一个方法，然后lua端直接调用一下，这两种都是可以的。
C#直接调用lua中模拟类这种用法很少见，不推荐使用。如有问题欢迎继续追问。
PS：Github有新消息现在不给我发邮件，没有及时的看到

**Comment by XINCGer** [comment]
> 暂时没时间验证，猜测一下： 1、中间类的问题，需要看里边做了啥 2、访问范围问题，你的第二种写法没加local 希望能帮到你.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "GITHUB243884919"<notifications@github.com>; 发送时间: 2019年4月28日(星期天) 下午3:15 收件人: "XINCGer/ColaFrameWork"<ColaFrameWork@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [XINCGer/ColaFrameWork] middleclass如何被c#调用的问题 (#4) StateLogin.lua如下，在Main.lua同目录 `local StateLogin = Class('StateLogin') function StateLogin.Enter() print("lua StateLogin Enter") end StateLogin = StateLogin:new() return StateLogin然后在c#代码中调用StateLogin.Entertolua报找不到这个函数的错误。 luaState.DoFile("Main.lua"); levelLoaded = luaState.GetFunction("OnLevelWasLoaded"); CallMain(); luaState.DoFile("StateLogin.lua"); luaState.GetFunction("StateLogin.Enter").Call();` 但是如果lua中我不用这个middleclass，而是直接用table的定义就没问题 StateLogin = {} function StateLogin:Enter() print("lua StateLogin Enter") end 请教下这是什么问题？如何解决 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

感谢热心老铁帮忙回复问题~

**Comment by GITHUB243884919** [comment]
> 你好，我来回答一下您的这个问题，在toLua中没有办法直接访问到local 的这种局部变量的。如果想要访问的话可以通过把你的类注册到一个全局的table中进行访问。比如将你的方法注册到UIManager的TestOpen中，然后就可以在C#端通过访问UIManger的方式进行访问了，代码如下：
> 
> ```cs
>         levelLoaded = luaState.GetFunction("OnLevelWasLoaded");
>         CallMain();
> 
>         LuaTable uiManager = luaState.GetTable("UIManager");
>         var func = uiManager.GetLuaFunction("TestOpen");
>         func.Call();
> ```
> 
> 或者你也可以将你的table通过某种方式传到C#中，并使用LuaTable类型的变量持有引用，然后在进行访问。不过不建议过多的进行C#和lua的这种穿梭操作，对性能消耗比较大，能完成的业务尽量就在lua端完成，或者在C#端封装一个方法，然后lua端直接调用一下，这两种都是可以的。
> C#直接调用lua中模拟类这种用法很少见，不推荐使用。如有问题欢迎继续追问。
> PS：Github有新消息现在不给我发邮件，没有及时的看到
非常感谢。我也非常同意你的观点，尽量在lua完成，除非有必要才进行lua和c#之间传输数据。

关于你说的 “C#端封装一个方法，然后lua端直接调用一下” 这种是不是用tolua导出class，然后在lua中调用。

**Comment by XINCGer** [comment]
> > 你好，我来回答一下您的这个问题，在toLua中没有办法直接访问到local 的这种局部变量的。如果想要访问的话可以通过把你的类注册到一个全局的table中进行访问。比如将你的方法注册到UIManager的TestOpen中，然后就可以在C#端通过访问UIManger的方式进行访问了，代码如下：
> > ```cs
> >         levelLoaded = luaState.GetFunction("OnLevelWasLoaded");
> >         CallMain();
> > 
> >         LuaTable uiManager = luaState.GetTable("UIManager");
> >         var func = uiManager.GetLuaFunction("TestOpen");
> >         func.Call();
> > ```
> > 
> > 
> > 或者你也可以将你的table通过某种方式传到C#中，并使用LuaTable类型的变量持有引用，然后在进行访问。不过不建议过多的进行C#和lua的这种穿梭操作，对性能消耗比较大，能完成的业务尽量就在lua端完成，或者在C#端封装一个方法，然后lua端直接调用一下，这两种都是可以的。
> > C#直接调用lua中模拟类这种用法很少见，不推荐使用。如有问题欢迎继续追问。
> > PS：Github有新消息现在不给我发邮件，没有及时的看到
> > 非常感谢。我也非常同意你的观点，尽量在lua完成，除非有必要才进行lua和c#之间传输数据。
> 
> 关于你说的 “C#端封装一个方法，然后lua端直接调用一下” 这种是不是用tolua导出class，然后在lua中调用。

是的，一些比较稳定的、有通用性质的业务逻辑完全可以封装到C#里面，lua直接调用接口即可，正确使用还能提高性能，减少GC
