### ISSUE TITLE
请问自带的skynet服务器能否升级到最新的5.4版本

### ISSUE THREAD

**Issue by owllyi** [XINCGer/ColaFrameWork#5]
不错的框架，学习啦。

同时，想问一下自带的skynet服务器是如何编译成windows版本的啊，能否介绍一下编译方法。skynet官方已经升级到5.4版本了，能否编译一份最新版本的同步上来呢，或者说下如何编译win版本的，我自己想试一下编译win版本。

**Comment by XINCGer** [comment]
用的是MinGW编译的，看下这个库：https://github.com/dpull/skynet-mingw
如果不想自己编译的话可以直接用它的自动化构建平台

**Comment by owllyi** [comment]
多谢啦，我先看下
